apiVersion: v1
kind: Service

metadata:
  name: svc-worpress
  labels:
    app: app-page

spec:
  type: NodePort # with this I can connect with internet
  selector:
    proyect: Wordpress_page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-wordpress
  labels:
    app: app-page

spec:
  selector:
    matchLabels:
      proyect: Wordpress_page
  replicas: 1

  template:
    metadata:
      name: wordpress
      labels:
        proyect: Wordpress_page
    spec:
      containers:
        - name: wordpress
          image: jarangos89/wordpress_image:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: svc-mariadb
            - name: WORDPRESS_DB_USER
              value: usuario_maria
            - name: WORDPRESS_DB_PASSWORD
              value: qwe098
            - name: WORDPRESS_DB_NAME
              value: datos_db
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage-wordpress
              mountPath: /var/www/html
      volumes:
        - name: persistent-storage-wordpress
          persistentVolumeClaim:
            claimName: pvc-wordpress
---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pvc-wordpress

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi